<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
	<TargetFramework>net8.0-windows</TargetFramework>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <AnalysisMode>Recommended</AnalysisMode>
	<EnableHotReload>true</EnableHotReload>
    <Deterministic>false</Deterministic>

    <!-- Assembly-Metadaten -->
    <AssemblyName>BlueBasics</AssemblyName>
    <RootNamespace>BlueBasics</RootNamespace>
    <AssemblyTitle>BlueBasics</AssemblyTitle>
    <Product>BlueBasics</Product>
    <Company>Christian Peter</Company>
    <Authors>Christian Peter</Authors>
    <Copyright>Copyright © 2026 Christian Peter</Copyright>

    <!-- Versionierung -->
    <AssemblyVersion>9.0.21022.0</AssemblyVersion>
    <FileVersion>9.0.21022.0</FileVersion>
    <Version>9.0.21022</Version>

     <!-- Plattformen -->
	 <Platforms>AnyCPU;x86;x64</Platforms>
    <UseWindowsForms>true</UseWindowsForms>
    <RepositoryUrl>https://github.com/cromagan/BlueElements</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

<ItemGroup>
  <!-- Code-Analyzer -->
  <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="9.0.0">
    <PrivateAssets>all</PrivateAssets>
    <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
  </PackageReference>

  <PackageReference Include="SonarAnalyzer.CSharp" Version="9.16.0.82469">
    <PrivateAssets>all</PrivateAssets>
    <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
  </PackageReference>
  
  <PackageReference Include="System.Text.Json" Version="10.0.6" />

</ItemGroup>

<ItemGroup>
  <PackageReference Include="System.Runtime.Caching" Version="8.0.0" />
  <PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
</ItemGroup>

  <ItemGroup>
    <None Remove="Ressources\Image\Icons\Aufklappen.png" />
    <None Remove="Ressources\Image\Icons\Auge.png" />
    <None Remove="Ressources\Image\Icons\MinusZeichen2.png" />
    <None Remove="Ressources\Image\Icons\PlusZeichen2.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Ressources\Image\Icons\Aufklappen.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Auge.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\BildmodusAbschneiden.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\BildmodusEinpassen.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\BildmodusVerzerren.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Bruchlinie.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Kopieren.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\EbeneNachHinten.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\EbeneNachVorne.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Excel.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Farben.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Farbrad.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Filmrolle.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Formel.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Gewicht.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Graustufen.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\GrößeÄndern.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Gänsefüßchen.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Hierarchie.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Hochformat.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Häkchen.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\HäkchenDoppelt.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\InDenHintergrund.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\InDenVordergrund.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Globus.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Kalender.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Karton.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Kontrast.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Kugel.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Layout.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Linksbündig.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Mauspfeil.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\MinusZeichen2.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Note.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\PDF.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Person.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Pipette.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\PlusZeichen2.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\PowerPoint.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Querformat.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Radiergummi.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Raster.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Rechtsbündig.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Refresh.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Schere.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Schloss.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Schlüssel.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\SeiteEinrichten.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Skript.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Smiley.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\SmileyUnhappy.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Spalte.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Summe.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Tabelle.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\TasteA.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\TasteABC.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\TasteESC.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\TasteProzent.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Textfeld.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Variable.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Visitenkarte.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Word.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Zeile.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Zeilenumbruch.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Zentrieren.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Zuschneiden.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Abspielen.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Aufnahme.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\AZ.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Bemaßung.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Binärdaten.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Blitz.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Brief.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Brille.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Datei.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Datenbank.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Diskette.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Drucker.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Eins.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Fernglas.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Frage.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Fragezeichen.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Ganzzahl.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Gleitkommazahl.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Herz.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Information.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Kamera.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Kamm.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Kreis.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Kreis2.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Kreuz.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Kritisch.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Lineal.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Linie.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Lupe.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\LupeMinus.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\LupePlus.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\MinusZeichen.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Ordner.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Pause.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Pfeil_Links.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Pfeil_Links_Scrollbar.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Pfeil_Oben.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Pfeil_Oben_Scrollbar.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Pfeil_Rechts.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Pfeil_Unten.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Pinnadel.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Pinsel.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\PlusZeichen.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Sonne.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Stift.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Stop.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Taschenrechner.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Textdatei.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Trichter.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Uhr.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Warnung.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Wolke.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\ZA.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\ZoomFit.png" />
    <EmbeddedResource Include="Ressources\Image\Steuerelemente\CheckBox.png" />
    <EmbeddedResource Include="Ressources\Image\Steuerelemente\CheckBox_Checked.png" />
    <EmbeddedResource Include="Ressources\Image\Steuerelemente\CheckBox_Checked_MouseOver.png" />
    <EmbeddedResource Include="Ressources\Image\Steuerelemente\CheckBox_Disabled.png" />
    <EmbeddedResource Include="Ressources\Image\Steuerelemente\CheckBox_Disabled_Checked.png" />
    <EmbeddedResource Include="Ressources\Image\Steuerelemente\CheckBox_MouseOver.png" />
    <EmbeddedResource Include="Ressources\Image\Steuerelemente\OptionBox.png" />
    <EmbeddedResource Include="Ressources\Image\Steuerelemente\OptionBox_Checked.png" />
    <EmbeddedResource Include="Ressources\Image\Steuerelemente\OptionBox_Checked_MouseOver.png" />
    <EmbeddedResource Include="Ressources\Image\Steuerelemente\OptionBox_Disabled.png" />
    <EmbeddedResource Include="Ressources\Image\Steuerelemente\OptionBox_Disabled_Checked.png" />
    <EmbeddedResource Include="Ressources\Image\Steuerelemente\OptionBox_MouseOver.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Clipboard.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\DrehenLinks.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\DrehenRechts.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\SpiegelnHorizontal.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\SpiegelnVertikal.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Stern.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Papierkorb.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Anwendung.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Bild.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Redo.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Undo.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Schild.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Telefon.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\XML.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Pfeil_Rechts_Scrollbar.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Pfeil_Unten_Scrollbar.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Feder.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Zahnrad.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Balken.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Klee.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Register.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Registersammlung.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Textfeld2.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Monitor.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Apfel.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Gruppe.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Verschieben.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Groupbox.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Schaltfläche.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Schriftart.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Puzzle.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Geldscheine.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Haus.png" />
    <EmbeddedResource Include="Ressources\Image\Icons\Einkaufswagen.png" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System" />
    <Using Include="System.Collections.Generic" />
    <Using Include="System.Drawing" />
    <Using Include="System.Drawing.Imaging" />
    <Using Include="System.Linq" />
    <Using Include="System.Text" />
    <Using Include="System.Reflection" />
    <Using Include="System.Globalization" />
    <Using Include="System.Text.Json" />
    <Using Include="System.Text.Json.Nodes" />
    <Using Include="BlueBasics.ClassesStatic" />
    <Using Include="BlueBasics.Enums" />
    <Using Include="BlueBasics.Interfaces" />
    <Using Include="BlueBasics.Extensions" Static="true" />
    <Using Include="BlueBasics.ClassesStatic.Generic" Static="true" />
    <Using Include="BlueBasics.ClassesStatic.Constants" Static="true" />
    <Using Include="BlueBasics.ClassesStatic.Converter" Static="true" />
  </ItemGroup>
</Project>
