//----------------------------------------------------------------------------------------
//	Copyright © 2003 - 2018 Tangible Software Solutions Inc.
//	This class can be used by anyone provided that the copyright notice remains intact.
//
//	This file replicates the behavior of VB's My.Application when the original VB project
//	did not include an autogenerated My.Application class.
//
//	Note: A reference to the Microsoft.VisualBasic assembly is required.
//----------------------------------------------------------------------------------------

namespace BeCreative.My
{
	internal class MyApplication : Microsoft.VisualBasic.ApplicationServices.ApplicationBase
	{
		[global::System.Diagnostics.DebuggerStepThroughAttribute()]
		public MyApplication() : base()
		{
		}

		private static MyApplication MyApp;
		internal static MyApplication Application
		{
			get
			{
				if (MyApp == null)
					MyApp = new MyApplication();

				return MyApp;
			}
		}
	}
}