// Authors:
// Christian Peter
//
// Copyright (c) 2025 Christian Peter
// https://github.com/cromagan/BlueElements
//
// License: GNU Affero General Public License v3.0
// https://github.com/cromagan/BlueElements/blob/master/LICENSE
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#nullable enable

namespace BlueBasics.Enums;

public enum ImageCode {

    //None,
    Abspielen,

    Anwendung,
    Aufnahme,
    AZ,
    Apfel,
    Balken,
    Bemaßung,
    Bild,
    BildmodusVerzerren,
    BildmodusAbschneiden,
    BildmodusEinpassen,
    Binärdaten,
    Blitz,
    Brief,
    Brille,
    Bruchlinie,
    Clipboard,
    Datei,
    Datenbank,
    Diskette,
    DrehenLinks,
    DrehenRechts,
    Drucker,
    EbeneNachHinten,
    EbeneNachVorne,
    Eins,
    Excel,
    Farben,
    Farbrad,
    Feder,
    Fernglas,
    Filmrolle,
    Formel,
    Frage,
    Fragezeichen,
    Gänsefüßchen,
    Ganzzahl,
    Gewicht,
    Gleitkommazahl,
    Globus,
    Graustufen,
    GrößeÄndern,
    Gruppe,
    Groupbox,
    Häkchen,
    HäkchenDoppelt,
    Herz,
    Hierarchie,
    Hochformat,
    InDenHintergrund,
    InDenVordergrund,
    Information,
    Kalender,
    Kamera,
    Kamm,
    Karton,
    Klee,
    Kontrast,
    Kopieren,
    Kreis,
    Kreis2,
    Kreuz,
    Kritisch,
    Kugel,
    Layout,
    Lineal,
    Linie,
    Linksbündig,
    Lupe,
    LupeMinus,
    LupePlus,
    Mauspfeil,
    MinusZeichen,
    Monitor,
    Note,
    Ordner,
    Papierkorb,
    Pause,
    PDF,
    Person,
    Pfeil_Links,
    Pfeil_Rechts,
    Pfeil_Oben,
    Pfeil_Unten,
    Pfeil_Links_Scrollbar,
    Pfeil_Oben_Scrollbar,
    Pfeil_Rechts_Scrollbar,
    Pfeil_Unten_Scrollbar,
    Pinsel,
    Pinnadel,
    Pipette,
    PlusZeichen,
    PowerPoint,
    Puzzle,
    Querformat,
    Radiergummi,
    Raster,
    Rechtsbündig,
    Redo,
    Refresh,
    Register,
    Registersammlung,
    Schaltfläche,
    Schere,
    Schild,
    Schloss,
    Schlüssel,
    Schriftart,
    SeiteEinrichten,
    Smiley,
    SmileyUnhappy,
    Skript,
    Sonne,
    Spalte,
    SpiegelnHorizontal,
    SpiegelnVertikal,
    Stern,
    Stift,
    Stop,
    Summe,
    Tabelle,
    Taschenrechner,
    TasteA,
    TasteABC,
    TasteESC,
    TasteProzent,
    Telefon,
    Textdatei,
    Textfeld,
    Textfeld2,
    Trichter,
    Uhr,
    Undo,
    Variable,
    Verschieben,
    Visitenkarte,
    Warnung,
    Wolke,
    Word,
    XML,
    ZA,
    Zahnrad,
    Zeile,
    Zeilenumbruch,
    Zentrieren,
    ZoomFit,
    Zuschneiden
    ////http://www.fileformat.info/info/emoji/list.htm
    ////Emoji
    // angry,
    // anguished,
    // blush,
    // broken_heart,
    // clap,
    // cold_sweat,
    // confused,
    // cry,
    // cupid,
    // disappointed,
    // dizzy_face,
    // flushed,
    // frowning,
    // grin,
    // heart,
    // heart_eyes,
    // hushed,
    // innocent,
    // joy,
    // kiss,
    // kissing_heart,
    // kissing_smiling_eyes,
    // laughing,
    // mask,
    // neutral_face,
    // no_entry_sign,
    // open_mouth,
    // pensive,
    // persevere,
    // punch,
    // relaxed,
    // relieved,
    // sleeping,
    // sleepy,
    // smiley,
    // smirk,
    // sob,
    // speech_balloon,
    // stuck_out_tongue_closed_eyes,
    // sunglasses,
    // sweat,
    // sweat_smile,
    // thought_balloon,
    // thumbsdown,
    // thumbsup,
    // tired_face,
    // triumph,
    // unamused,
    // weary,
    // wink,
    // worried,
    // yum,
    // Globals
    // sphere
}